# Avoid editing this file
# Future updates may include changes to this file but once you edit
# this file it will no longer be auto-updated and you will not
# benefit from the improvements without manual intervention

# If you want to edit min/max/initial/tol/etc
# Do that in the file custom.ini

items:
- key: APSTAT
  description: Status of auto pilot, Avaliable or not
  type: str
  tol: 10000
  initial: INIT
- key: APMODE
  description: Mode of auto pilot, Heading Hold (CRUISE), Trim (Manual), AUTO fly to waypoint
  type: str
  initial: TRIM
  tol: 10000
- key: APMSG
  description: Auto Pilot Message for pilot
  type: str
  initial: ""
- key: APWPV
  description: Does AP have a valid waypoint to navigate to
  type: bool
  initial: False
- key: APREQ
  description: Mode of auto pilot that is requested
  type: str
  initial: "INIT"
- key: APADJ
  description: Adjust heading/altitude of auto pilot using trim controls
  type: bool
  initial: False

# Used by ifly and mavlink
- key: WPLAT
  description: Waypoint Latitude
  type: float
  initial: 0.0
  min: -90
  max: 90
  tol: 50000
- key: WPLON
  description: Waypoint Longitude
  type: float
  initial: 0.0
  min: -90
  max: 90
  tol: 50000
- key: WPNAME
  description: Waypoint Name
  type: str
  tol: 50000
  initial: ""
- key: WPHEAD
  description: Heading to waypoint
  type: str
  tol: 50000
  initial: ""

