include: 
- database/variables.yaml

entries:

- key: EGTBTNg
  description: EGT Button %b
  type: bool
  tol: 0

- key: IAS
  description: Indicated Airspeed
  type: float
  min: 0.0
  max: 1000.0
  units: knots
  initial: 0.0
  tol: 2000
  aux: [Min,Max,V1,V2,Vne,Vfe,Vmc,Va,Vno,Vs,Vs0,Vx,Vy]

- key: IASW
  description: Indicated Airspeed Warning
  type: int
  min: 0
  max: 5
  units: warninglevel
  initial: 0
  tol: 2000

- key: TAS
  description: True Airspeed
  type: float
  min: 0.0
  max: 2000.0
  units: knots
  initial: 0.0
  tol: 2000

- key: CAS
  description: True Airspeed
  type: float
  min: 0.0
  max: 2000.0
  units: knots
  initial: 0.0
  tol: 2000

- key: GS
  description: Ground Speed
  type: float
  min: 0.0
  max: 2000.0
  units: knots
  initial: 0.0
  tol: 2000

- key: ALT
  description: Indicated Altitude
  type: float
  min: -2000.0
  max: 60000.0
  units: ft
  initial: 0.0
  tol: 2000

- key: PALT
  description: Pressure Altitude
  type: float
  min: -1000.0
  max: 60000.0
  units: ft
  initial: 0.0
  tol: 2000

- key: TALT
  description: True Altitude
  type: float
  min: -1000.0
  max: 60000.0
  units: ft
  initial: 0.0
  tol: 2000

- key: DALT
  description: Density Altitude
  type: float
  min: -1000.0
  max: 60000.0
  units: ft
  initial: 0.0
  tol: 2000

- key: AGL
  description: Radar Altitude (Above Ground Level)
  type: float
  min: -1000.0
  max: 60000.0
  units: ft
  initial: 0.0
  tol: 2000

- key: BARO
  description: Altimeter Setting
  type: float
  min: 0.0
  max: 35.0
  units: inHg
  initial: 29.92
  tol: 2000

- key: AIRPRESS
  description: Air Pressure
  type: float
  min: 0.0
  max: 200000.0
  units: Pa
  initial: 101325.0
  tol: 2000

- key: DIFFAIRPRESS
  description: Differential Air Pressure
  type: float
  min: 0.0
  max: 200000.0
  units: Pa
  initial: 101325.0
  tol: 2000

- key: VS
  description: Vertical Speed
  type: float
  min: -30000.0
  max: 30000.0
  units: ft/min
  initial: 0.0
  tol: 2000
  aux: [Min,Max]

- key: RAT
  description: MGL RDAC Air Temperature
  type: float
  min: -100.0
  max: 100.0
  units: degC
  initial: 0.0
  tol: 2000
  aux: [Min,Max,lowWarn]

- key: OAT
  description: Outside Air Temperature
  type: float
  min: -100.0
  max: 100.0
  units: degC
  initial: 0.0
  tol: 2000
  aux: [Min,Max,lowWarn]

- key: CAT
  description: Cabin Air Temperature
  type: float
  min: -100.0
  max: 100.0
  units: degC
  initial: 0.0
  tol: 2000
  aux: [Min,Max,lowWarn,highWarn,lowAlarm,highAlarm]

- key: CTLPTCH
  description: Pitch Control
  type: float
  min: -1.0
  max: 1.0
  units: '%/100'
  initial: 0.0
  tol: 200

- key: CTLROLL
  description: Roll Control
  type: float
  min: -1.0
  max: 1.0
  units: '%/100'
  initial: 0.0
  tol: 200

- key: CTLYAW
  description: Yaw Control (Rudder)
  type: float
  min: -1.0
  max: 1.0
  units: '%/100'
  initial: 0.0
  tol: 200

- key: CTLCOLL
  description: Collective Control
  type: float
  min: -1.0
  max: 1.0
  units: '%/100'
  initial: 0.0
  tol: 200

- key: CTLATP
  description: AntiTorque Pedal Ctrl
  type: float
  min: -1.0
  max: 1.0
  units: '%/100'
  initial: 0.0
  tol: 200

- key: OATW
  description: Outside Air Temperature Warning
  type: int
  min: 0
  max: 5
  units: warninglevel
  initial: 0
  tol: 2000

- key: CTLFLAP
  description: Flap Control
  type: float
  min: -1.0
  max: 1.0
  units: '%/100'
  initial: 0.0
  tol: 200

- key: CTLLBRK
  description: Left Brake Control
  type: float
  min: 0.0
  max: 1.0
  units: '%/100'
  initial: 0.0
  tol: 200

- key: CTLRBRK
  description: Right Brake Control
  type: float
  min: 0.0
  max: 1.0
  units: '%/100'
  initial: 0.0
  tol: 1000

- key: ANORM
  description: Normal Acceleration
  type: float
  min: -30.0
  max: 30.0
  units: g
  initial: 0.0
  tol: 200

- key: ALAT
  description: Lateral Acceleration
  type: float
  min: -30.0
  max: 30.0
  units: g
  initial: 0.0
  tol: 200

- key: ALONG
  description: Longitudinal Acceleration
  type: float
  min: -30.0
  max: 30.0
  units: g
  initial: 0.0
  tol: 200

- key: FUELQt
  description: Fuel Quantity Tank %t
  type: float
  min: 0.0
  max: 200.0
  units: gal
  initial: 0.0
  tol: 2000
  aux: [Min,Max,lowWarn,lowAlarm]

- key: FUELQT
  description: Total Fuel Quantity
  type: float
  min: 0.0
  max: 200.0
  units: gal
  initial: 0.0
  tol: 2000
  aux: [Min,Max,lowWarn,lowAlarm]

- key: LAT
  description: Latitude
  type: float
  min: -90.0
  max: 90.0
  units: deg
  initial: 0.0
  tol: 20000

- key: LONG
  description: Longitude
  type: float
  min: -180.0
  max: 180.0
  units: deg
  initial: 0.0
  tol: 20000


- key: FTIME
  description: Flight Time
  type: float
  min: 0.0
  max: 1000.0
  initial: 0.0

- key: DIM
  description: Panel Dimmer Level
  type: int
  min: 0
  max: 100
  initial: 100

- key: HOBBS1
  description: Total Engine Time %e
  type: float
  min: 0.0
  max: 100000.0
  units: Hours
  initial: 0.0

- key: ACID
  description: Aircraft Identification
  type: str
  tol: 0

- key: BTNAP
  description: AP button state
  type: bool
  initial: false
- key: BTNHH
  description: AP heading hold button state
  type: bool
  initial: false
- key: BTNFP
  description: AP flight plan button state
  type: bool
  initial: false
- key: APSTAT
  description: Status of auto pilot, Avaliable or not
  type: str
  tol: 10000
  initial: INIT
- key: APMODE
  description: Mode of auto pilot, Heading Hold (CRUISE), Trim (Manual), AUTO fly to waypoint
  type: str
  initial: TRIM
  tol: 10000
- key: APMSG
  description: Auto Pilot Message for pilot
  type: str
  initial: ""
- key: APWPV
  description: Does AP have a valid waypoint to navigate to
  type: bool
  initial: False
- key: APREQ
  description: Mode of auto pilot that is requested
  type: str
  initial: "INIT"
- key: APADJ
  description: Adjust heading/altitude of auto pilot using trim controls
  type: bool
  initial: False

# Used by ifly and mavlink
- key: WPLAT
  description: Waypoint Latitude
  type: float
  initial: 0.0
  min: -90
  max: 90
  tol: 50000
- key: WPLON
  description: Waypoint Longitude
  type: float
  initial: 0.0
  min: -90
  max: 90
  tol: 50000
- key: WPNAME
  description: Waypoint Name
  type: str
  tol: 50000
  initial: ""
- key: WPHEAD
  description: Heading to waypoint
  type: str
  tol: 50000
  initial: ""


- include: database/generic.yaml
- include: database/ahrs.yaml
- include: database/com_radio.yaml
- include: database/engine.yaml
- include: database/trims.yaml

- include: database/system.yaml
- include: database/last.yaml

